# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b99f7d34b7d46a4b0aceb91513eee81489641d41938251741dae5a16ef8824b55d875176d9d874f66bfe2fd03d8c74e9b1a15c2f6bbb1645961df5f53173d088

test:
  secret_key_base: 6281b838b1834630977c298d81fe277eefe5eb18606fa01883d65d5c9f874573a590a9f55a20eebb088cf12239875738945808477381f4c2d61ead90009c03aa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
